# OBC2 CONFIGURATION FILE

# SERIAL
SERIAL:
  PORT_OBC1: "172.16.18.180"

# EXPERIMENTS
EXPERIMENT:
  
  AI:
    PACKET_COUNTER: 1
    SAMPLE_TIME: 0
    SAMPLING_RATE: 10
    BAUDRATE: 115200
    TIMEOUT: 10000
    PORT: "/dev/ttyUSB0"
    WDT: 10
    EXCEPTIONS: 0
    SEQUENCE_LENGTH: 50
    MODEL_PATH: /home/retina/Desktop/retinabexus/lattepanda/Input/intero_modello_trainvalimix_100hs_2nl_100sl_lr3_wd5_drop4_batch128.pt
    SCALER_PATH: /home/retina/Desktop/retinabexus/lattepanda/Input/scaler_trainvalimix_100hs_2nl_100sl_lr3_wd5_drop4_batch128.pkl
  GNSS:
    PACKET_COUNTER: 1
    PORT: "/dev/ttyUSB1"
    BAUDRATE: 115200
    TIMEOUT: 10

# Packets
PACKETS:

  AI:
    ABS_PATH: "/home/retina/Desktop/retinabexus/lattepanda/Output/AI/"
    FIELDNAMES: ['ID', 'Type', 'Number', 'Datetime [UTC]', 'GyroX [rad/s]', 'GyroY [rad/s]', 'GyroZ [rad/s]', 
                      'AccX [m/s^2]', 'AccY [m/s^2]', 'AccZ [m/s^2]', 'MagX', 'MagY', 'MagZ', 'q0', 'q1', 'q2', 'q3', 'qe0', 'qe1', 'qe2', 'qe3']
    FILE_LENGTH: 10000

  GNSS:
    ABS_PATH: "/home/retina/Desktop/retinabexus/lattepanda/Output/GNSS/"
    FIELDNAMES: ['ID', 'Type', 'Number', 'Datetime [UTC]', 'Carrier phase 1', 'Pseudorange 1', 'Doppler 1', 
                      'Carrier phase 2', 'Pseudorange 2', 'Doppler 2', 'Latitude', 'Longitude', 'Altitude']
    FILE_LENGTH: 10000


  UPLINK:
    PORT: "/dev/ttyUSB0"
    BAUDRATE: 115200
    
  FEEDBACKS:
    FILE_PATH: "/home/retina/Desktop/retinabexus/lattepanda/Output/feedbacks.txt"
