#############################################################################
# OBC1 CONFIGURATION FILE

# Socket
SOCKET:
  IP_GS : "192.168.2.157" 
  PORT_GS: 5050
  PORT_GNSS-SDR: 1234

# GNSS-SDR
GNSS-SDR:
  1: 
    CMD: 'gnss-sdr -c /home/strains/romulus/confs/L1_L2_recorderOnly.conf'
    ENABLED: 0
  2: 
    CMD: 'gnss-sdr -c /home/strains/romulus/confs/L1_L2_recorder2.conf'
    ENABLED: 0  

# Packets
PACKETS:

  GNSS-SDR:
    EXPERIMENT_ID: "ERRE"
    PACKET_ID: "GNSS-SDR"
    TIMEOUT: 5.
    SEND_PROCESSED: 0
    BUFFERSIZE: 2048
    SLEEPTIME: 0.2
    #ABS_PATH: "/media/romulusSSD/data_processed/"
    ABS_PATH: "/home/strains/OBS1/outputs/"
    FIELDNAMES: ["ID","Type","Number","Date","cpu_temp","system","signal","prn","channel_id","acq_delay_samples","acq_doppler_hz","acq_samplestamp_samples","acq_doppler_step","flag_valid_acquisition","fs","prompt_i","prompt_q",
                 "cn0_db_hz","carrier_doppler_hz","carrier_phase_rads","code_phase_samples","tracking_sample_counter","flag_valid_symbol_output","correlation_length_ms","flag_valid_word",
                 "tow_at_current_symbol_ms","pseudorange_m","rx_time","flag_valid_pseudorange","interp_tow_ms","flag_PLL_180_deg_phase_locked"]
    DATA_LENGTH: 31
    FILE_LENGTH: 216

  COMMANDS:
    EXPERIMENT_ID: "ERRE"
    PACKET_ID: "CMD"
    TIMEOUT: 10.
    BUFFERSIZE: 128
    FILENAME: "/home/strains/OBS1/outputs/commands.csv"
    FIELDNAMES: ['ID', 'Type', 'Packet Number', 'Datetime', 'Command']
    DATA_LENGTH: 5

  FEEDBACKS:
    EXPERIMENT_ID: "ERRE"
    PACKET_ID: "FDB"
    TIMEOUT: 10.
    BUFFERSIZE: 128
    FILENAME: "/home/strains/OBS1/outputs/feedbacks.csv"
    FIELDNAMES: ['ID', 'Type', 'Packet Number', 'Datetime', 'Feedback']
    DATA_LENGTH: 5

#############################################################################


